repos:
  - repo: local
    hooks:
      - id: fourmolu
        name: fourmolu
        entry: fourmolu --mode=inplace
        language: system
        files: '\.(hs|hs-boot)$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
