name:                opencv-imghash
version:             0.1.0.0
license:             BSD-3-Clause
author:              Takahiro HIMURA
maintainer:          taka@himura.jp
copyright:           "2023 Takahiro HIMURA"
homepage:            https://himura.jp/gitlab/cgrepos-haskell
git:                 git@himura.jp:cgrepos-haskell.git

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/himura/opencv-imghash#readme>

language: GHC2021

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PackageImports
- QuasiQuotes
- RecordWildCards
- StrictData
- TypeFamilies

library:
  source-dirs: src

tests:
  opencv-imghash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opencv-imghash





