name:                opencv-imghash
version:             0.1.0.0
license:             BSD-3-Clause
author:              Takahiro HIMURA
maintainer:          taka@himura.jp
copyright:           "2023 Takahiro HIMURA"
homepage:            https://himura.jp/gitlab/cgrepos-haskell
git:                 git@himura.jp:cgrepos-haskell.git

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/himura/opencv-imghash#readme>

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- containers
- inline-c
- inline-c-cpp
- bytestring
- bindings-DSL

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PackageImports
- QuasiQuotes
- RecordWildCards
- StrictData
- TypeFamilies

library:
  source-dirs: src

  cxx-options: -std=c++11

  when:
    - condition: os(linux)
      extra-libraries: stdc++
    - condition: os(darwin)
      extra-libraries: c++
      # See: https://ghc.haskell.org/trac/ghc/ticket/11829
      ld-options: -Wl,-keep_dwarf_unwind

  pkgconfig-depends: opencv4 >= 4.0.0

executables:
  sample:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Werror
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opencv-imghash

tests:
  opencv-imghash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opencv-imghash
